modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/jaredlll08/Ambient-Environment/issues"
[[mods]]
modId="ambientenvironment"
version="${file.jarVersion}"
displayName="Ambient Environment"
credits="MC Bedrock edition lol"
authors="Jaredlll08"
updateJSONURL="https://updates.blamejared.com/get?n=AmbientEnvironment&gv=1.18.2"
description='''
Adds more ambiance to the game
'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/ambient-environment"